openapi: '3.0.2'
info:
  title: DNDApi
  description: "Nossa API de armas de D&D fornece informações sobre as várias armas que podem ser encontradas no sistema de RPG de mesa: Dungeons & Dragons. Ela inclui detalhes como nome da arma, alcance, quantidade de dano e tipo de dano causado, além das propriedades presentes na mesma."
  version: '1.0'
servers:
  - url: https://api.server.test/api
paths:
  /api:
    get:
      description: Lista todas as rotas da API.
      responses:
        '200':
          description: Rotas listadas com sucesso.
          content:
  /api/armas:
    get:
      description: Lista todas as armas.
      responses:
        '200':
          description: Armas listadas com sucesso.
          content:
    post:
      description: Cria uma nova arma.
      responses:
        '201':
          description: Arma criada com sucesso.
        '400':
          description: Erro de validação, falta algum parâmetro na requisição.
        '403':
          description: Erro de autenticação, token inválido ou sem permissão necessária.
  /api/armas/{index}:
    get:
      description: Lista uma arma específica.
      responses:
        '200':
          description: Arma listada com sucesso.
          content:
    put:
      description: Atualiza uma arma específica.
      responses:
        '200':
          description: Atualização realizada com sucesso.
        '400':
          description: Erro de validação, falta algum parâmetro na requisição.
        '403':
          description: Erro de autenticação, token inválido ou sem permissão necessária.
    delete:
      description: Deleta uma arma específica.
      responses:
        '200':
          description: Arma deletada com sucesso.
        '403':
          description: Erro de autenticação, token inválido ou sem permissão necessária.
        '404':
          description: Arma não encontrada ou inexistente.